#!/bin/bash
#
# Test the Perl image in the OpenShift.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# VERSION specifies a version of the Perl in the candidate image.
# The image has to be available before this script is executed.

THISDIR=$(dirname ${BASH_SOURCE[0]})

source "${THISDIR}/test-lib.sh"
source "${THISDIR}/test-lib-openshift.sh"
source "${THISDIR}/test-lib-perl.sh"
source "${THISDIR}/test-lib-remote-openshift.sh"


TEST_LIST="\
test_perl_s2i_sample_app
test_perl_s2i_dancer_app
test_perl_s2i_templates
test_perl_imagestream
test_latest_imagestreams
"

trap ct_os_cleanup EXIT SIGINT

ct_os_set_ocp4 || exit $OC_ERR

ct_os_check_compulsory_vars || exit $OC_ERR

ct_os_check_login || exit $OC_ERR

ct_os_tag_image_for_cvp "perl"

set -ux

# For testing on OpenShift 4 we use internal registry
export CT_OCP4_TEST=true

test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
test -n "${VERSION-}" || false 'make sure $VERSION is defined'

TEST_SUMMARY=''
TEST_SET=${TESTS:-$TEST_LIST} ct_run_tests_from_testset "openshift-remote-cluster"

# vim: set tabstop=2:shiftwidth=2:expandtab:

